[forest]
parameters = [
    {weight=1, value=0},
    {weight=0.5, value=0.2}
]
layers = [
    {below-sea-level=false, height=1, block="base:grass_block"},
    {below-sea-level=false, height=7, block="base:dirt"},
    {height=10, block="base:cobblestone"},
    {height=3, block="base:granite"},
    {height=2, block="base:diorite"},
    {height=5, block="base:cobblestone"},
    {height=4, block="base:granite"},
    {height=3, block="base:diorite"},
    {height=-1, block="base:cobbled_deepslate"},
    {y=-64, height=1, block="base:basalt"}
]
sea-layers = [
    {y=-1, height=1, block="base:water"}
]
plant-chance = 0.4
plants = [
    {weight=1, block="base:grass"},
    {weight=0.03, block="base:flower"}
]
structure-chance = 0.032
structures = [
    {name="tree0", weight=1},
    {name="tree1", weight=1},
    {name="tree2", weight=1},
    {name="tower", weight=0.002}
]
cave-chance = 0.05
cave-blocks = [
    {block="core:air", weight=100},
    {block="base:cobblestone", weight=10},
    {block="base:granite", weight=5},
    {block="base:diorite", weight=5},
    {block="base:cobbled_deepslate", weight=20},
    {y=-64, height=1, block="base:basalt"}
]
cave-size = {min=3, max=16}

[desert]
parameters = [
    {weight=1.0, value=1},
    {weight=0.8, value=0}
]
layers = [
    {height=6, block="base:sand"},
    {height=8, block="base:cobblestone"},
    {height=4, block="base:granite"},
    {height=5, block="base:cobblestone"},
    {height=3, block="base:diorite"},
    {height=-1, block="base:cobbled_deepslate"},
    {y=-64, height=1, block="base:basalt"}
]
sea-layers = [
    {y=-1, height=1, block="base:water"}
]
cave-chance = 0.04
cave-blocks = [
    {block="core:air", weight=100},
    {block="base:cobblestone", weight=15},
    {block="base:sandstone", weight=8},
    {block="base:cobbled_deepslate", weight=20},
    {y=-64, height=1, block="base:basalt"}
]
cave-size = {min=2, max=16}

[plains]
parameters = [
    {weight=0.8, value=0.5},
    {weight=0.8, value=0.0}
]
layers = [
    {below-sea-level=false, height=1, block="base:grass_block"},
    {below-sea-level=false, height=5, block="base:dirt"},
    {height=6, block="base:cobblestone"},
    {height=3, block="base:granite"},
    {height=2, block="base:diorite"},
    {height=4, block="base:cobblestone"},
    {height=2, block="base:granite"},
    {height=-1, block="base:cobbled_deepslate"},
    {y=-64, height=1, block="base:basalt"}
]
sea-layers = [
    {y=-1, height=1, block="base:water"}
]
plant-chance = 0.3
plants = [
    {weight=1, block="base:grass"},
    {weight=0.03, block="base:flower"}
]
structure-chance = 0.0001
structures = [
    {name="tree0", weight=1},
    {name="tree1", weight=1}
]
cave-chance = 0.06
cave-blocks = [
    {block="core:air", weight=100},
    {block="base:cobblestone", weight=8},
    {block="base:granite", weight=3},
    {block="base:cobbled_deepslate", weight=20},
    {y=-64, height=1, block="base:basalt"}
]
cave-size = {min=4, max=12}